name: Android Unit Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Create Google Services JSON
    - name: Create Google Services JSON
      working-directory: app
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        ls -la
        touch google-services.json
        echo $DATA > google-services.json
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
